nefurehouse:
  debug: false
  directLinkPrefix: directlink
  repoFolder: E:\Temp\house_link
  log:
    path: .nefurehouse/logs
  tmp:
    path: .nefurehouse/tmp
    pieceSizeMb: 1
    autoDelete: true
  house: .nefurehouse
  cache:
    auto-refresh:
      interval: 1
    timeout: 60
  constant:
    readme: readme.md
    password: password.txt
  preview:
    audio:
      maxFileSizeMb: 5
    text:
      maxFileSizeKb: 512
  json:
    systemConfig: json/systemConfig.json
  downloadThreadPool:
    maxPoolSize: 8
    corePoolSize: 8
    queueCapacity: 12
    aliveSeconds: 60
  uploadThreadPool:
    maxPoolSize: 8
    corePoolSize: 8
    queueCapacity: 12
    aliveSeconds: 60
server:
  port: 8080
  servlet:
    context-path: ''
  tomcat:
    threads:
      max: 20
  compression:
    enabled: true

spring:
  datasource:
    #MySQL 配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/house?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
    username: nefure
    password: 123456

  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8

  profiles:
    active: prod


mybatis:
  #别名包（方便在映射文件中直接写类名）
  type-aliases-package: org.nefure.nefurehouse.model.entity
  configuration:
    map-underscore-to-camel-case: true
